FROM ruby:2.6.1

RUN apt-get update -qq && apt-get install -y build-essential

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
ADD Gemfile* $APP_HOME/

RUN bundle install --without development production

ADD . $APP_HOME
ENV RACK_ENV=test

CMD ["bundle", "exec", "rake", "test"]
